name: ci

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]
      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
